### ISSUE TITLE
Zone Bypass - Payload response sent in any case

### ISSUE THREAD

**Issue by thanomichalis** [caronc/ultrasync#31]
The payload for the zone bypass, ise sent in any case regardless the vendor.

That as a results gives an log error:
2023-05-08 13:18:04.581 ERROR (SyncWorker_6) [ultrasync] Failed to query http://[internal IP address]/user/zonefunction.cgi

The checking of the zone starts in main.py file in line 592. Then there are if statements for each vendor, but the sent of the payload, is done inside the if statements. However, there is another sent payload after the if statements (line 637), which creates the bug.
This must be deleted.

I have created a pull request to resolve the bug.

**Comment by thanomichalis** [comment]
Hi @caronc , i had copied manually the main.py so that to run the tests, but today with the new update of HA, it seems that the changes, although you bumped the version, were not passed to HACS, like last time.

**Comment by caronc** [comment]
try now

**Comment by thanomichalis** [comment]
nope. I see you bumped to 0.9.8 the ultrasync and to 1.0.3 the HA integration, however still in HA the latest is the 1.0.2 version of the HA integration, which obviously, downloads the 0.9.7 of the ultrasync.

**Comment by thanomichalis** [comment]
Yeap… it is working!!!!

thank you
